server:
  port: 9001

spring:
  application:
    name: kuke-board-comment-service

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: ENC(UFQeqTye1HXbE/hmxLhWOQ==)
    password: ENC(mDdrvWKtgc8b5ACRa6jdTw==)

  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace  # 파라미터 바인딩
    
jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}


