spring:
  jpa:
    # JPA에서 사용하는 데이터베이스 종류
    database: h2
    open-in-view: false
    # SQL 쿼리를 로그에 출력하도록 설정
    show-sql: true
    hibernate:
      # 시작 시 데이터베이스 스키마를 자동으로 생성하도록 설정
      ddl-auto: create
    properties:
      hibernate:
        #  SQL 쿼리를 가독성 있게 포맷하여 출력하도록 설정
        format_sql: true
        # default_batch_fetch_size: 10

  # 데이터베이스 연결 설정
  datasource:
    url: jdbc:h2:mem:portfolio
    username: sa
    password:
    driver-class-name: org.h2.Driver

  # H2 데이터베이스의 웹 콘솔을 활성화하는 설정
  h2:
    console:
      enabled: true
      # 콘솔 url : http://localhost:8080/h2-console
      path: /h2-console
