CREATE INDEX "C##ARTICLE_SVC".IDX_TB_ARTICLE_01
    ON "C##ARTICLE_SVC".TB_ARTICLE (BOARD_ID, ARTICLE_ID DESC);

CREATE INDEX "C##COMMENT_SVC".IDX_TB_COMMENT_01
    ON "C##COMMENT_SVC".TB_COMMENT (ARTICLE_ID, PARENT_COMMENT_ID, COMMENT_ID DESC);
