/* 테이블 생성 */
CREATE TABLE TB_ARTICLE (
      ARTICLE_ID     NUMBER(19)        PRIMARY KEY
    , TITLE          VARCHAR2(100)     NOT NULL
    , CONTENT        VARCHAR2(3000)
    , BOARD_ID       NUMBER(19)        NOT NULL
    , WRITER_ID      NUMBER(19)        NOT NULL
    , CREATED_AT     DATE              DEFAULT SYSDATE
    , MODIFIED_AT    DATE
);

COMMENT ON TABLE TB_ARTICLE IS '게시글';

COMMENT ON COLUMN TB_ARTICLE.ARTICLE_ID   IS '게시글ID';
COMMENT ON COLUMN TB_ARTICLE.TITLE        IS '제목';
COMMENT ON COLUMN TB_ARTICLE.CONTENT      IS '내용';
COMMENT ON COLUMN TB_ARTICLE.BOARD_ID     IS '게시판ID (Shard Key)';
COMMENT ON COLUMN TB_ARTICLE.WRITER_ID    IS '작성자ID';
COMMENT ON COLUMN TB_ARTICLE.CREATED_AT   IS '생성시간';
COMMENT ON COLUMN TB_ARTICLE.MODIFIED_AT  IS '수정시간';