/* 스키마 생성 */
GRANT CREATE SESSION TO C##LIKE_SVC;
ALTER USER C##LIKE_SVC QUOTA UNLIMITED ON USERS;

/* 테이블 생성 */
CREATE TABLE "C##LIKE_SVC".TB_LIKE (
    ARTICLE_LIKE_ID NUMBER(19) PRIMARY KEY,
    ARTICLE_ID      NUMBER(19) NOT NULL,
    USER_ID         NUMBER(19) NOT NULL,
    CREATED_AT      DATE NOT NULL
);
COMMENT ON TABLE "C##LIKE_SVC".TB_LIKE IS '좋아요';
COMMENT ON COLUMN "C##LIKE_SVC".TB_LIKE.ARTICLE_LIKE_ID   IS '좋아요ID';
COMMENT ON COLUMN "C##LIKE_SVC".TB_LIKE.ARTICLE_ID   IS '게시글ID(Shard Key)';
COMMENT ON COLUMN "C##LIKE_SVC".TB_LIKE.USER_ID    IS '작성자ID';
COMMENT ON COLUMN "C##LIKE_SVC".TB_LIKE.CREATED_AT   IS '생성시간';

/* 인덱스 생성 */
CREATE UNIQUE INDEX "C##LIKE_SVC".IDX_TB_LIKE_01
    ON "C##LIKE_SVC".TB_LIKE (ARTICLE_ID ASC, USER_ID ASC);

