/* 스키마 생성 */
GRANT CREATE SESSION TO C##COMMENT_SVC;
ALTER USER C##COMMENT_SVC QUOTA UNLIMITED ON USERS;

/* 테이블 생성 */
CREATE TABLE "C##COMMENT_SVC".TB_COMMENT (
      COMMENT_ID         NUMBER(19)        PRIMARY KEY
    , CONTENT            VARCHAR2(3000)    NOT NULL
    , ARTICLE_ID         NUMBER(19)        NOT NULL
    , PARENT_COMMENT_ID  NUMBER(19)        NOT NULL
    , WRITER_ID          NUMBER(19)        NOT NULL
    , DEL_YN             VARCHAR2(1)       DEFAULT 'N' NOT NULL
    , CREATED_AT         DATE              DEFAULT SYSDATE NOT NULL
    , MODIFIED_AT    DATE
);
COMMENT ON TABLE "C##COMMENT_SVC".TB_COMMENT IS '댓글';
COMMENT ON COLUMN "C##COMMENT_SVC".TB_COMMENT.COMMENT_ID   IS '댓글ID';
COMMENT ON COLUMN "C##COMMENT_SVC".TB_COMMENT.CONTENT      IS '내용';
COMMENT ON COLUMN "C##COMMENT_SVC".TB_COMMENT.ARTICLE_ID   IS '게시판ID (Shard Key)';
COMMENT ON COLUMN "C##COMMENT_SVC".TB_COMMENT.PARENT_COMMENT_ID IS '상위댓글ID';
COMMENT ON COLUMN "C##COMMENT_SVC".TB_COMMENT.WRITER_ID    IS '작성자ID';
COMMENT ON COLUMN "C##COMMENT_SVC".TB_COMMENT.DEL_YN       IS '삭제여부';
COMMENT ON COLUMN "C##COMMENT_SVC".TB_COMMENT.CREATED_AT   IS '생성시간';
COMMENT ON COLUMN "C##COMMENT_SVC".TB_COMMENT.MODIFIED_AT  IS '수정시간';

/* 인덱스 생성 */
CREATE INDEX "C##COMMENT_SVC".IDX_TB_COMMENT_01
    ON "C##COMMENT_SVC".TB_COMMENT (ARTICLE_ID, PARENT_COMMENT_ID, COMMENT_ID DESC);
